config/routes.rb
Rails.application.routes.draw do

   root 'asgndrafts#index'

end

app/models/asgnmodel.rb
class Asgnmodel < ActiveRecord::Base
end

app/models/cmpt276a2.rb
class Cmpt276a2 < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/asgndrafts_controller.rb
class AsgndraftsController < ApplicationController
  before_action :set_asgnmodels, only: [:show, :edit, :update, :destroy]

  # GET /asgndrafts
  # GET /asgndrafts.json
  def index
    @asgnmodels = Asgnmodels.all
  end

  # GET /asgndrafts/1
  # GET /asgndrafts/1.json
  def show
  end

  # GET /asgndrafts/new
  def new
    @asgnmodels = Asgnmodels.new
  end

  # GET /asgndrafts/1/edit
  def edit
  end

  # POST /asgndrafts
  # POST /asgndrafts.json
  def create
    @asgnmodels = Asgnmodels.new(asgndraft_params)

    respond_to do |format|
      if @asgnmodels.save
        format.html { redirect_to @asgnmodels, notice: 'Asgndraft was successfully created.' }
        format.json { render action: 'show', status: :created, location: @asgnmodels }
      else
        format.html { render action: 'new' }
        format.json { render json: @asgnmodels.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asgndrafts/1
  # PATCH/PUT /asgndrafts/1.json
  def update
    respond_to do |format|
      if @asgndraft.update(asgndraft_params)
        format.html { redirect_to @asgndraft, notice: 'Asgndraft was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @asgndraft }
      else
        format.html { render action: 'edit' }
        format.json { render json: @asgndraft.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asgndrafts/1
  # DELETE /asgndrafts/1.json
  def destroy
    @asgndraft.destroy
    respond_to do |format|
      format.html { redirect_to asgndrafts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asgndraft
      @asgndraft = Asgndraft.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asgndraft_params
      params.require(:asgndraft).permit(:name, :weight, :height, :color, :dateofbirth, :numberoflanguagesspoken)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/asgndrafts/_form.html.erb
<%= form_for(@asgndraft) do |f| %>
  <% if @asgndraft.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asgndraft.errors.count, "error") %> prohibited this asgndraft from being saved:</h2>

      <ul>
      <% @asgndraft.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :dateofbirth %><br>
    <%= f.datetime_select :dateofbirth %>
  </div>
  <div class="field">
    <%= f.label :numberoflanguagesspoken %><br>
    <%= f.number_field :numberoflanguagesspoken %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/asgndrafts/edit.html.erb
<h1>Editing Asgndraft</h1>

<%= render 'form' %>

<%= link_to 'Show', @asgndraft %> |
<%= link_to 'Back', asgndrafts_path %>

app/views/asgndrafts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Asgndrafts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Weight</th>
      <th>Height</th>
      <th>Color</th>
      <th>Dateofbirth</th>
      <th>Numberoflanguagesspoken</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @asgndrafts.each do |asgnmodels| %>
      <tr>
        <td><%= asgnmodels.name %></td>
        <td><%= asgnmodels.weight %></td>
        <td><%= asgnmodels.height %></td>
        <td><%= asgnmodels.color %></td>
        <td><%= asgnmodels.dateofbirth %></td>
        <td><%= asgnmodels.numberoflanguagesspoken %></td>
        <td><%= link_to 'Show', asgnmodels %></td>
        <td><%= link_to 'Edit', edit_asgnmodels_path(asgnmodels) %></td>
        <td><%= link_to 'Destroy', asgnmodels, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asgndraft', new_asgnmodels_path %>

app/views/asgndrafts/new.html.erb
<h1>New Asgndraft</h1>

<%= render 'form' %>

<%= link_to 'Back', asgndrafts_path %>

app/views/asgndrafts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @asgndraft.name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @asgndraft.weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @asgndraft.height %>
</p>

<p>
  <strong>Color:</strong>
  <%= @asgndraft.color %>
</p>

<p>
  <strong>Dateofbirth:</strong>
  <%= @asgndraft.dateofbirth %>
</p>

<p>
  <strong>Numberoflanguagesspoken:</strong>
  <%= @asgndraft.numberoflanguagesspoken %>
</p>

<%= link_to 'Edit', edit_asgndraft_path(@asgndraft) %> |
<%= link_to 'Back', asgndrafts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>C276A2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>